### ISSUE TITLE
This doesn't work for me

### ISSUE THREAD

**Issue by igfloz** [LocuraDU/DU-DamageReport#1]
I've also left a comment on du creators

Doesn't work for me ( Damage Report v3.35)
2 warnings pop up in the Lua window
Warning: method clear() is depreciated
Warning: method setSVG(svg) is depreciated

Then it shuts down (nothing on screen)

please note, If I switch from html display to Lua display I get "render script error" message on screen

**Comment by igfloz** [comment]
........ Lua error on screen reads <render script error>

**Comment by CredenceHamby** [comment]
Its hard to reply to comments on DUC as we dont get notifications from the site.

"please note, If I switch from html display to Lua display I get "render script error" message on screen"

This is not what switching to HTML means... There is a page in the wiki about how to use HTML in game.

The warnings wont stop the script from running its just changes they made in last update of game.

**Comment by igfloz** [comment]
oh right, I'll go try and find that info

**Comment by CredenceHamby** [comment]
INSTALL: https://github.com/LocuraDU/DU-DamageReport/wiki/Installation

HTML: https://github.com/LocuraDU/DU-DamageReport/wiki/Enable-HTML

**Comment by CredenceHamby** [comment]
Script was just tested with a fresh install yesterday after new update and is still working.

**Comment by igfloz** [comment]
2nd link is painfully simple - I'll re-log and test

**Comment by CredenceHamby** [comment]
May need to do a reinstallation and follow the directions carefully. Its pretty picky about the set up because of how NQ does the slot links.

**Comment by igfloz** [comment]
It's all working - Many thanks for quick response.  Is cargo and sys still in the pipeline ?

**Comment by CredenceHamby** [comment]
It is however my #1 goal right now is getting it updated to remove HTML and convert to LUA since they are trying to shut HTML down completely. That's why it's got errors after last update letting you know those functions aren't being supported. It's still working, just they are letting us know it's going away.
